# Compression configuration for Qwen-3-30B-A3B
# Target: 20-30% compression ratio

# Low-rank adapter configuration
rank: 64  # Adjust based on desired compression ratio

# Zero-shot initialization parameters
num_steps: 1000  # Optimization steps for reconstruction
lr: 1e-3  # Learning rate for Adam optimizer

# Parallelization settings
num_layers: null  # Will be inferred from model config
parallel_mode: true  # Use parallel GPU compression

