# Evaluation Configuration

# Tasks to evaluate
tasks:
  wikitext: -1 # perplexity evaluation
  # mmlu: 5 #world knowledge
  # hellaswag: 10 #common sense
  # piqa: 5 #physical commonsense
  # arc_easy: 25 #grade school science
  # arc_challenge: 25 #grade school science
  # gsm8k: 5 #math


# Evaluation settings
batch_size: auto  # Let the system decide based on GPU memory


# Async evaluation settings
async_eval:
  eval_interval: 60  # Check for new checkpoints every 60 seconds
  n_gpus_per_model: 2  # Number of GPUs to use per model during evaluation


